headersOrigin = "config"
plugins = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "/Users/lucy/clawd/216-16-website"
publishOrigin = "config"
base = "/Users/lucy/clawd/216-16-website"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"